export var CREATED_MESSAGE = "CREATED_MESSAGE";
export var CREATING_MESSAGE = "CREATING_MESSAGE";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_FAIL = "LOAD_MESSAGES_FAIL";
